language: python
python:
    - "2.6"
    - "2.7"
    # See https://github.com/rgalanakis/hostthedocs/pull/24 for details
    # - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install:
  - pip install tox-travis
script:
  - tox
